[alias]
xclippy = [
  "clippy",
  "--workspace",
  "--all-targets",
  "--",
  "-Dwarnings",
  "-Wclippy::all",
  "-Aclippy::unit_arg",
  "-Aclippy::eval-order-dependence",
  "-Aclippy::new-without-default",
  "-Aclippy::rc_buffer",
  "-Aclippy::upper_case_acronyms",
  "-Aclippy::len-without-is-empty",
  "-Aclippy::from-iter-instead-of-collect",
  "-Aclippy::while-let-on-iterator",
  "-Aclippy::bool-assert-comparison",
  "-Aclippy::needless-collect",
  "-Aclippy::enum-variant-names",
  "-Aclippy::self-named-constructors",
]

[build]
rustflags = ["--cfg", "tokio_unstable"]

# This is a temporary workaround to avoid multiple library
# definitions for LZ4 (caused by rocksdb).
# This will be removed once rocksdb provides a fix, see:
# https://github.com/rust-rocksdb/rust-rocksdb/issues/666
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition"]
